# Generated by Django 2.2.8 on 2022-07-06 13:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cytometers',
            fields=[
                ('cytometer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cytometer_label', models.CharField(max_length=15, unique=True)),
                ('cytometer_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'populateDB_cytometers',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150, unique=True)),
                ('department_email', models.EmailField(blank=True, max_length=254)),
                ('department_phoneNumber', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'populateDB_departments',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_label', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'populateDB_devices',
            },
        ),
        migrations.CreateModel(
            name='Dictionarys',
            fields=[
                ('dict_id', models.AutoField(primary_key=True, serialize=False)),
                ('dict_label', models.CharField(max_length=100, unique=True)),
                ('dict_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'populateDB_dictionarys',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_abbr', models.CharField(max_length=10, unique=True)),
                ('desensitization_note', models.CharField(blank=True, max_length=255)),
                ('desensitization_allergen', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'populateDB_donors',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('bat_id', models.AutoField(primary_key=True, serialize=False)),
                ('bat_name', models.CharField(max_length=150, unique=True)),
                ('date_of_measurement', models.DateField()),
                ('beadExperiment', models.BooleanField()),
                ('specialExperiment', models.BooleanField()),
                ('specialNotes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('cytometer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Cytometers')),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Devices')),
            ],
            options={
                'db_table': 'populateDB_experiment',
            },
        ),
        migrations.CreateModel(
            name='ExperimentFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('allergen', models.CharField(blank=True, max_length=20, null=True)),
                ('bat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Experiment')),
            ],
            options={
                'db_table': 'populateDB_experimentFiles',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'populateDB_fileType',
            },
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_shortName', models.CharField(max_length=15, unique=True)),
                ('institute_name', models.CharField(blank=True, max_length=150)),
                ('institute_address', models.CharField(blank=True, max_length=150)),
                ('institute_email', models.EmailField(blank=True, max_length=254)),
                ('institute_phoneNumber', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'populateDB_institutes',
            },
        ),
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('marker_id', models.AutoField(primary_key=True, serialize=False)),
                ('marker_label', models.CharField(max_length=100, unique=True)),
                ('marker_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'populateDB_markers',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'populateDB_projects',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Label', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.ExperimentFiles')),
            ],
            options={
                'db_table': 'populateDB_MetaData',
            },
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.FileType'),
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Donor'),
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Projects'),
        ),
        migrations.CreateModel(
            name='Experimenters',
            fields=[
                ('experimenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('experimenter_label', models.CharField(max_length=10, unique=True)),
                ('experimenter_firstName', models.CharField(blank=True, max_length=100)),
                ('experimenter_lastName', models.CharField(blank=True, max_length=100)),
                ('experimenter_email', models.EmailField(blank=True, max_length=254)),
                ('experimenter_phoneNumber', models.CharField(blank=True, max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Departments')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Institutes')),
            ],
            options={
                'db_table': 'populateDB_experimenters',
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='experimenter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Experimenters'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Institutes'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='marker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Markers'),
        ),
        migrations.AddField(
            model_name='departments',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.Institutes'),
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('pnn', models.CharField(blank=True, max_length=50)),
                ('pns', models.CharField(blank=True, max_length=50)),
                ('bat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Experiment')),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Donor')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.Projects')),
            ],
            options={
                'db_table': 'populateDB_channels',
            },
        ),
    ]
