# Generated by Django 3.2.8 on 2023-07-04 13:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisMarkers',
            fields=[
                ('analysisMarker_id', models.AutoField(primary_key=True, serialize=False)),
                ('chosen_z1', models.CharField(blank=True, max_length=20, null=True)),
                ('chosen_y1', models.CharField(blank=True, max_length=20, null=True)),
                ('chosen_z2', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('analysis_start_time', models.TimeField(blank=True, null=True)),
                ('analysis_end_time', models.TimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Error', 'Error')], max_length=120, null=True)),
                ('analysis_type', models.CharField(blank=True, choices=[('Auto Bat', 'Auto Bat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True)),
                ('analysis_type_version', models.CharField(blank=True, choices=[('Auto Bat', 'Auto Bat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True)),
                ('analysis_error', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('analysis_info_messages', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalClass_Names',
            fields=[
                ('clinicalClass_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinicalClass_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150, unique=True)),
                ('department_email', models.EmailField(blank=True, max_length=254)),
                ('department_phoneNumber', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_label', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_abbr', models.CharField(max_length=10, unique=True)),
                ('desensitization_note', models.CharField(blank=True, max_length=255)),
                ('desensitization_allergen', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, max_length=300, null=True, upload_to='')),
                ('allergen', models.CharField(blank=True, max_length=50, null=True)),
                ('control', models.CharField(blank=True, choices=[('Negative control', 'Negative control'), ('Primary Positive control', 'Primary Positive control'), ('Secondary Positive control', 'Secondary Positive control'), ('Allergen', 'Allergen')], max_length=120, null=True)),
                ('analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('panel_name', models.CharField(max_length=15, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles')),
            ],
        ),
        migrations.CreateModel(
            name='MeanRawData',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('labels', models.CharField(blank=True, max_length=200, null=True)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('institute_id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_shortName', models.CharField(max_length=15, unique=True)),
                ('institute_name', models.CharField(blank=True, max_length=150)),
                ('institute_address', models.CharField(blank=True, max_length=150)),
                ('institute_email', models.EmailField(blank=True, max_length=254)),
                ('institute_phoneNumber', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilesPlots',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_path', models.TextField(max_length=500, unique=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Experimenters',
            fields=[
                ('experimenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('experimenter_label', models.CharField(max_length=10, unique=True)),
                ('experimenter_firstName', models.CharField(blank=True, max_length=100)),
                ('experimenter_lastName', models.CharField(blank=True, max_length=100)),
                ('experimenter_email', models.EmailField(blank=True, max_length=254)),
                ('experimenter_phoneNumber', models.CharField(blank=True, max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.departments')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.institutes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('bat_id', models.AutoField(primary_key=True, serialize=False)),
                ('bat_name', models.CharField(max_length=150, unique=True)),
                ('date_of_measurement', models.DateField()),
                ('beadExperiment', models.BooleanField()),
                ('specialExperiment', models.BooleanField()),
                ('specialNotes', models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)])),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.devices')),
                ('experimenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimenters')),
                ('institute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.institutes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_sIgE',
            fields=[
                ('sige_id', models.AutoField(primary_key=True, serialize=False)),
                ('wheat_flour', models.FloatField(blank=True, null=True)),
                ('gluten', models.FloatField(blank=True, null=True)),
                ('gliadin', models.FloatField(blank=True, null=True)),
                ('Tri_a_19', models.FloatField(blank=True, null=True)),
                ('Tri_a_14', models.FloatField(blank=True, null=True)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_OFC',
            fields=[
                ('ofc_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_ofc', models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_clinical_old',
            fields=[
                ('donor_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_clinicalClass_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.clinicalclass_names')),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='institute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='populateDB.institutes'),
        ),
        migrations.AddField(
            model_name='departments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('pnn', models.CharField(blank=True, max_length=50)),
                ('pns', models.CharField(blank=True, max_length=50)),
                ('analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisThresholds',
            fields=[
                ('thresHolds_id', models.AutoField(primary_key=True, serialize=False)),
                ('SSCA_Threshold', models.FloatField(blank=True, null=True)),
                ('FcR_Threshold', models.FloatField(blank=True, null=True)),
                ('CD63_Threshold', models.FloatField(blank=True, null=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redQ4', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('blackQ2', models.FloatField(blank=True, null=True)),
                ('blackQ3', models.FloatField(blank=True, null=True)),
                ('blackQ4', models.FloatField(blank=True, null=True)),
                ('zmeanQ4', models.FloatField(blank=True, null=True)),
                ('z1_min', models.FloatField(blank=True, null=True)),
                ('z1_max', models.FloatField(blank=True, null=True)),
                ('msi_Y', models.FloatField(blank=True, null=True)),
                ('cellQ4', models.FloatField(blank=True, null=True)),
                ('responder', models.CharField(blank=True, choices=[('NA', 'NA'), ('aIgE Responder', 'aIgE Responder'), ('aIgE None_Responder', 'aIgE None_Responder'), ('fMLP Responder', 'fMLP Responder'), ('fMLP None_Responder', 'fMLP None_Responder')], max_length=120, null=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='populateDB.experimentfiles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField(max_length=500, unique=True)),
                ('file_type', models.CharField(blank=True, choices=[('PNG', 'PNG'), ('PDF', 'PDF'), ('Excel', 'Excel')], max_length=120, null=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='bat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experiment'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='panel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.panels'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
