# Generated by Django 3.2.8 on 2022-12-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisFiles',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField(max_length=500, unique=True)),
                ('file_type', models.CharField(blank=True, choices=[('PNG', 'PNG'), ('PDF', 'PDF'), ('Excel', 'Excel')], max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisMarkers',
            fields=[
                ('analysisMarker_id', models.AutoField(primary_key=True, serialize=False)),
                ('chosen_z1', models.CharField(blank=True, max_length=20, null=True)),
                ('chosen_y1', models.CharField(blank=True, max_length=20, null=True)),
                ('chosen_z2', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_date', models.DateField(blank=True, null=True)),
                ('analysis_start_time', models.TimeField(blank=True, null=True)),
                ('analysis_end_time', models.TimeField(blank=True, null=True)),
                ('analysis_status', models.CharField(blank=True, choices=[('Waitting', 'Waitting'), ('In Progress', 'In Progress'), ('Ready', 'Ready')], max_length=120, null=True)),
                ('analysis_type', models.CharField(blank=True, choices=[('Auto Bat', 'Auto Grat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True)),
                ('analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redQ4', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('blackQ2', models.CharField(blank=True, max_length=20, null=True)),
                ('blackQ3', models.CharField(blank=True, max_length=20, null=True)),
                ('blackQ4', models.CharField(blank=True, max_length=20, null=True)),
                ('zmeanQ4', models.CharField(blank=True, max_length=20, null=True)),
                ('CD63min', models.CharField(blank=True, max_length=20, null=True)),
                ('CD63max', models.CharField(blank=True, max_length=20, null=True)),
                ('msiCCR3', models.CharField(blank=True, max_length=20, null=True)),
                ('cellQ4', models.CharField(blank=True, max_length=20, null=True)),
                ('responder', models.CharField(blank=True, max_length=20, null=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('pnn', models.CharField(blank=True, max_length=50)),
                ('pns', models.CharField(blank=True, max_length=50)),
                ('analysis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='FilesPlots',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_path', models.TextField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeanRawData',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('labels', models.CharField(blank=True, max_length=200, null=True)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labels', models.CharField(blank=True, max_length=200)),
                ('values', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserRegistrationModel',
            new_name='AddUser',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='cytometer_id',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='marker_id',
        ),
        migrations.RemoveField(
            model_name='experimentfiles',
            name='bat_id',
        ),
        migrations.RemoveField(
            model_name='experimentfiles',
            name='donor_id',
        ),
        migrations.RemoveField(
            model_name='experimentfiles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experimentfiles',
            name='panel_id',
        ),
        migrations.RemoveField(
            model_name='experimentfiles',
            name='type_id',
        ),
        migrations.AddField(
            model_name='devices',
            name='device_label',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='allergen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='control',
            field=models.CharField(blank=True, choices=[('Negative control', 'Negative control'), ('Primary Positive control', 'Primary Positive control'), ('Secondary Positive control', 'Secondary Positive control'), ('Allergen', 'Allergen')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.devices'),
        ),
        migrations.AlterField(
            model_name='experimentfiles',
            name='file_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='panels',
            name='panel_name',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterModelTable(
            name='departments',
            table=None,
        ),
        migrations.AlterModelTable(
            name='devices',
            table=None,
        ),
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='experiment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='experimenters',
            table=None,
        ),
        migrations.AlterModelTable(
            name='experimentfiles',
            table=None,
        ),
        migrations.AlterModelTable(
            name='institutes',
            table=None,
        ),
        migrations.AlterModelTable(
            name='panels',
            table=None,
        ),
        migrations.DeleteModel(
            name='Cytometers',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='Markers',
        ),
        migrations.AddField(
            model_name='metadata',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles'),
        ),
        migrations.AddField(
            model_name='meanrawdata',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles'),
        ),
        migrations.AddField(
            model_name='filesplots',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles'),
        ),
        migrations.AddField(
            model_name='analysisfiles',
            name='analysisMarker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='bat_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experiment'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='panel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.panels'),
        ),
        migrations.AddField(
            model_name='experimentfiles',
            name='analysis_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis'),
        ),
    ]
