# Generated by Django 3.2.8 on 2023-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='analysis_type_version',
            field=models.CharField(blank=True, choices=[('Auto Bat', 'Auto Grat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
