# Generated by Django 3.2.8 on 2023-07-04 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorClass_clinical_old',
            new_name='DonorClass_clinical',
        ),
    ]
