# Generated by Django 3.2.8 on 2023-02-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0002_auto_20230123_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysis'),
        ),
    ]
