# Generated by Django 3.2.8 on 2022-12-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0002_auto_20221207_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfiles',
            name='analysisMarker_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='analysisMarker_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='channels',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experimentfiles',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filesplots',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meanrawdata',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='file_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
