# Generated by Django 3.2.8 on 2023-07-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0002_rename_donorclass_clinical_old_donorclass_clinical'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorclass_clinical',
            name='donor_clinicalClass_id_old',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
