# Generated by Django 3.2.8 on 2023-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0003_alter_analysismarkers_analysis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
