# Generated by Django 3.2.8 on 2023-08-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0004_auto_20230704_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='chosen_z2_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='zMarker',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
