# Generated by Django 3.2.8 on 2023-08-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0005_auto_20230801_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisthresholds',
            old_name='CD63_Threshold',
            new_name='X_Threshold',
        ),
        migrations.RenameField(
            model_name='analysisthresholds',
            old_name='FcR_Threshold',
            new_name='Y_Threshold',
        ),
        migrations.RenameField(
            model_name='analysisthresholds',
            old_name='SSCA_Threshold',
            new_name='Z2_1_Threshold',
        ),
        migrations.AddField(
            model_name='analysisthresholds',
            name='Z2_2_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
