# Generated by Django 3.2.8 on 2023-08-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0006_auto_20230801_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfiles',
            name='file_name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
