# Generated by Django 3.2.8 on 2023-02-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0006_auto_20230202_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresults',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.experimentfiles'),
        ),
    ]
