# Generated by Django 3.2.8 on 2023-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0007_alter_experimentfiles_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfiles',
            name='allergen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experimentfiles',
            name='file_name',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
