# Generated by Django 3.2.8 on 2023-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0007_analysisresults_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('Auto Bat', 'Auto Bat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_type_version',
            field=models.CharField(blank=True, choices=[('Auto Bat', 'Auto Bat'), ('Auto Grat', 'Auto Grat')], max_length=120, null=True),
        ),
    ]
