# Generated by Django 3.2.8 on 2023-02-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0008_auto_20230202_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresults',
            name='file_name',
        ),
    ]
