# Generated by Django 3.2.8 on 2023-08-02 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0008_auto_20230801_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTest_SPT',
            fields=[
                ('spt_id', models.AutoField(primary_key=True, serialize=False)),
                ('Histamine', models.FloatField(blank=True, null=True)),
                ('NaCl', models.FloatField(blank=True, null=True)),
                ('wheat_flour', models.FloatField(blank=True, null=True)),
                ('wheat_gluten', models.FloatField(blank=True, null=True)),
                ('birch', models.FloatField(blank=True, null=True)),
                ('mugworth', models.FloatField(blank=True, null=True)),
                ('timothy', models.FloatField(blank=True, null=True)),
                ('house_dust_mite', models.FloatField(blank=True, null=True)),
                ('cat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorTestBlood',
            fields=[
                ('testBlood_id', models.AutoField(primary_key=True, serialize=False)),
                ('gIgE', models.FloatField(blank=True, null=True)),
                ('wheat_flour', models.FloatField(blank=True, null=True)),
                ('gluten', models.FloatField(blank=True, null=True)),
                ('gliadin', models.FloatField(blank=True, null=True)),
                ('Tri_a_19', models.FloatField(blank=True, null=True)),
                ('Tri_a_14', models.FloatField(blank=True, null=True)),
                ('Tryptase', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorTestOFC',
            fields=[
                ('ofc_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_ofc', models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True)),
                ('gram_limit_ofc', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DonorTestOFC_exercise',
            fields=[
                ('ofc_exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_ofc_exercise', models.CharField(blank=True, choices=[('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True)),
                ('gram_limit_ofc_exercise', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='donorclass_sige',
            name='donor_id',
        ),
        migrations.RemoveField(
            model_name='donorclass_sige',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_age_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_age_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_sex',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='DonorClass_OFC',
        ),
        migrations.DeleteModel(
            name='DonorClass_sIgE',
        ),
        migrations.AddField(
            model_name='donortestofc_exercise',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='donortestofc_exercise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donortestofc',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='donortestofc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donortestblood',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='donortestblood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donortest_spt',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor'),
        ),
        migrations.AddField(
            model_name='donortest_spt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
