# Generated by Django 3.2.8 on 2023-08-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0009_auto_20230802_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorclass_clinical',
            name='donor_clinicalClass_id_old',
        ),
    ]
