# Generated by Django 3.2.8 on 2023-02-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0009_remove_analysisresults_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentfiles',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
