# Generated by Django 3.2.8 on 2023-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0011_auto_20230223_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='responder',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('aIgE Responder', 'aIgE Responder'), ('aIgE None_Responder', 'aIgE None_Responder'), ('fMLP Responder', 'fMLP Responder'), ('fMLP None_Responder', 'fMLP None_Responder')], max_length=120, null=True),
        ),
    ]
