# Generated by Django 3.2.8 on 2023-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0011_auto_20230802_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donortestofc',
            name='gram_limit_ofc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
