# Generated by Django 3.2.8 on 2023-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0012_alter_donortestofc_gram_limit_ofc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donortestofc_exercise',
            name='gram_limit_ofc_exercise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
