# Generated by Django 3.2.8 on 2023-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0013_alter_analysisresults_responder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='redQ4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
