# Generated by Django 3.2.8 on 2023-08-03 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0013_alter_donortestofc_exercise_gram_limit_ofc_exercise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorClinicalClass',
            new_name='DonorClass_clinical',
        ),
    ]
