# Generated by Django 3.2.8 on 2023-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0014_alter_analysisresults_redq4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='CD63max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='CD63min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='blackQ2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='blackQ3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='blackQ4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='cellQ4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='msiCCR3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresults',
            name='zmeanQ4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
