# Generated by Django 3.2.8 on 2023-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0014_rename_donorclinicalclass_donorclass_clinical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorclass_clinical',
            name='clinicalClass_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
