# Generated by Django 3.2.8 on 2023-08-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0015_alter_donorclass_clinical_clinicalclass_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorClinicalclass',
            fields=[
                ('DonorClinicalClass_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinicalClass_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.clinicalclass_names')),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
