# Generated by Django 3.2.8 on 2023-03-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0015_auto_20230309_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_status',
            field=models.CharField(blank=True, choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Ready', 'Ready'), ('Error', 'Error')], max_length=120, null=True),
        ),
    ]
