# Generated by Django 3.2.8 on 2023-08-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0016_donorclinicalclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorClass_clinical',
        ),
    ]
