# Generated by Django 3.2.8 on 2023-04-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0016_alter_analysismarkers_analysis_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisThresholds',
            fields=[
                ('thresHolds_id', models.AutoField(primary_key=True, serialize=False)),
                ('markerxThreshold', models.CharField(blank=True, max_length=20, null=True)),
                ('markerYThreshold', models.CharField(blank=True, max_length=20, null=True)),
                ('markerZ1Threshold', models.CharField(blank=True, max_length=20, null=True)),
                ('analysisMarker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers')),
            ],
        ),
    ]
