# Generated by Django 3.2.8 on 2023-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0017_delete_donorclass_clinical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='zMarker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
