# Generated by Django 3.2.8 on 2023-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0017_analysisthresholds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisthresholds',
            name='markerYThreshold',
        ),
        migrations.RemoveField(
            model_name='analysisthresholds',
            name='markerZ1Threshold',
        ),
        migrations.RemoveField(
            model_name='analysisthresholds',
            name='markerxThreshold',
        ),
        migrations.AddField(
            model_name='analysisthresholds',
            name='CD63_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisthresholds',
            name='FcR_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisthresholds',
            name='SSCA_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
