# Generated by Django 3.2.8 on 2023-05-10 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0018_auto_20230427_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='analysis_error',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
