# Generated by Django 3.2.8 on 2023-08-29 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0018_alter_analysisresults_zmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='analysis_manualThresholds',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_info_messages',
            field=models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='analysismarkers',
            name='analysis_type_version',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
