# Generated by Django 3.2.8 on 2023-10-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0020_alter_analysismarkers_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.departments'),
        ),
        migrations.AddField(
            model_name='adduser',
            name='institute_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.institutes'),
        ),
    ]
