# Generated by Django 3.2.8 on 2023-05-19 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('populateDB', '0021_alter_experiment_date_of_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SP2SP3_Names',
            fields=[
                ('sp2sp3_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp2sp3_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_SP2SP3',
            fields=[
                ('sp2sp3class_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('donor_sp2sp3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.sp2sp3_names')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_sIgE',
            fields=[
                ('sige_id', models.AutoField(primary_key=True, serialize=False)),
                ('wheat_flour', models.FloatField(blank=True, null=True)),
                ('gluten', models.FloatField(blank=True, null=True)),
                ('gliadin', models.FloatField(blank=True, null=True)),
                ('Tri_a_19', models.FloatField(blank=True, null=True)),
                ('Tri_a_14', models.FloatField(blank=True, null=True)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorClass_OFC',
            fields=[
                ('ofc_id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_ofc', models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True)),
                ('donor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.donor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
