# Generated by Django 3.2.8 on 2023-10-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0021_auto_20231012_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='chosen_z2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
