# Generated by Django 3.2.8 on 2023-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0022_alter_analysismarkers_chosen_z2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysismarkers',
            name='chosen_z2_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
