# Generated by Django 3.2.8 on 2023-05-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0022_donorclass_ofc_donorclass_sige_donorclass_sp2sp3_sp2sp3_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SP2SP3_Names',
            new_name='ClinicalClass_Names',
        ),
        migrations.RenameField(
            model_name='clinicalclass_names',
            old_name='sp2sp3_id',
            new_name='clinicalClass_id',
        ),
        migrations.RenameField(
            model_name='clinicalclass_names',
            old_name='sp2sp3_name',
            new_name='clinicalClass_name',
        ),
        migrations.DeleteModel(
            name='DonorClass_SP2SP3',
        ),
    ]
