# Generated by Django 3.2.8 on 2023-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0023_alter_analysismarkers_chosen_z2_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisthresholds',
            name='Z2_3_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisthresholds',
            name='Z2_4_Threshold',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
