# Generated by Django 3.2.8 on 2023-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0024_donorclass_clinical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorclass_sige',
            name='Tri_a_14',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='Tri_a_19',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='gliadin',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='gluten',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='wheat_flour',
            field=models.CharField(blank=True, choices=[('NA', 'NA'), ('positive', 'positive'), ('negative', 'negative')], max_length=120, null=True),
        ),
    ]
