# Generated by Django 3.2.8 on 2023-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0024_auto_20231017_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentfiles',
            name='control',
            field=models.CharField(blank=True, choices=[('Negative control', 'Negative control'), ('Primary Positive control', 'Primary Positive control'), ('Secondary Positive control', 'Secondary Positive control'), ('Unstained', 'Unstained'), ('Allergen', 'Allergen')], max_length=120, null=True),
        ),
    ]
