# Generated by Django 3.2.8 on 2023-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0025_auto_20230523_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorclass_sige',
            name='Tri_a_14',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='Tri_a_19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='gliadin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='gluten',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorclass_sige',
            name='wheat_flour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
