# Generated by Django 3.2.8 on 2023-05-25 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0026_auto_20230525_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='analysis_info_messages',
            field=models.TextField(blank=True, max_length=250, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
