# Generated by Django 3.2.8 on 2023-06-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0027_analysismarkers_analysis_info_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='populateDB.experimentfiles'),
        ),
    ]
