# Generated by Django 3.2.8 on 2024-01-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0027_analysis_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysismarkers',
            name='analysis_symbol_pdf',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
