# Generated by Django 3.2.8 on 2024-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0028_analysismarkers_analysis_symbol_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismarkers',
            name='analysis_symbol_pdf',
        ),
        migrations.AddField(
            model_name='analysisresults',
            name='plot_symbol',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
