# Generated by Django 3.2.8 on 2023-06-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0028_alter_analysisresults_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresults',
            old_name='CD63max',
            new_name='msi_Y',
        ),
        migrations.RenameField(
            model_name='analysisresults',
            old_name='CD63min',
            new_name='z1_max',
        ),
        migrations.RenameField(
            model_name='analysisresults',
            old_name='msiCCR3',
            new_name='z1_min',
        ),
    ]
