# Generated by Django 3.2.8 on 2023-06-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0029_auto_20230612_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesplots',
            name='analysisMarker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='populateDB.analysismarkers'),
        ),
    ]
