# Generated by Django 3.2.8 on 2024-03-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populateDB', '0031_rename_id_analysisresults_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='thresholds_checks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
